name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  pull_request:
    branches:
      - main
    paths:
      - docs/**

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Astro
        id: build
        uses: withastro/action@v3
        with:
          path: ./docs
          node-version: 20
          package-manager: pnpm@latest

      - name: Create Summary
        if: github.event_name == 'pull_request' && (success() || failure())
        id: summary
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "Step | Outcome" >> $GITHUB_OUTPUT
          echo "| -- | -- |" >> $GITHUB_OUTPUT
          echo "| Build Astro | ${{ steps.build.outcome }} |" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      - name: Push Summary to Pull Request
        if: steps.summary.conclusion == 'success' && (success() || failure())
        uses: actions/github-script@v7
        env:
          SUMMARY: "${{ steps.summary.outputs.summary }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

  deploy:
    name: Deploy
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages     
        id: deploy
        uses: actions/deploy-pages@v4